### ISSUE TITLE
find best react component ecosystems

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/dogstack#13]
what's important:

- consistent usage api
- good documentation
- meets accessibility standards
- minimal code
- uses fela (or is otherwise compatible)
- is tested

what components do we need?

- [ ] side navigation (hamburger)
- [ ] modal
- [ ] accordion
- [ ] ...?

**Comment by ahdinosaur** [comment]
https://react-component.github.io/badgeboard/

**Comment by ahdinosaur** [comment]
table: https://github.com/tannerlinsley/react-table

**Comment by ahdinosaur** [comment]
https://carbon-ui.com/

**Comment by ahdinosaur** [comment]
@simontegg started using [ant.design](https://ant.design/), and now is using [Semantic UI](http://react.semantic-ui.com/introduction)

the reason Semantic UI is great is that every component supports `className`, which means it works great with `fela`. i'm keen to give this a try. /cc @gregorykan

**Comment by ahdinosaur** [comment]
ended up going with http://material-ui.com/ for Cobuy. it's the most popular, is theme-able in js (Semantic UI and ant.design both require less to modify theme), supports `className`, and is shiny as. :sparkles: 

i figure it's better to get some `dogstack`-y components up using Material than try to immediately roll our own components, as we can learn what we want to do differently later once we know what components are important.

**Comment by simontegg** [comment]
My hesitation around Material was the inline styles implementation https://github.com/callemall/material-ui/issues/1132

I'm now also looking at blueprint js 

[date range picker](http://blueprintjs.com/docs/#datetime/daterangepicker ) 
[editable text](http://blueprintjs.com/docs/#core/components/editable-text)
