### ISSUE TITLE
question:  do we want static type checking?

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/dogstack#47]
using FlowType or TypeScript or neither?

**Comment by ahdinosaur** [comment]
if we go with json schema:

- https://github.com/dannynelson/json-schema-to-flow-type
- https://github.com/bcherny/json-schema-to-typescript

**Comment by ahdinosaur** [comment]
or tcomb:

- https://github.com/gcanti/babel-plugin-tcomb

**Comment by ahdinosaur** [comment]
or https://github.com/gcanti/io-ts

**Comment by simontegg** [comment]
Another type checking solution https://github.com/maiavictor/forall

**Comment by simontegg** [comment]
After reading the the `forall` you could have a runtime type checking in plain js then just use dead code elimination for your production builds to remove it. 

The `gen-io-ts` approach is pretty flexible and like the idea of defining types in jsonschema or swagger. Dogstack projects wouldn't have to adopt TypeScript but they easily could if they wanted. 
I also see benefits in defining entity types in jsonschema as the source of type truth and leveraging the schema for an auto CRUD form interface builder a la Rails or Phoenix
