### ISSUE TITLE
idempotent services

### ISSUE THREAD

**Issue by ahdinosaur** [root-systems/dogstack#56]
trivial example: we use our client ids to ensure an operation only happens once

references:

- http://www.servicedesignpatterns.com/WebServiceInfrastructures/IdempotentRetry
- https://softwareengineering.stackexchange.com/questions/320143/should-an-idempotent-service-always-return-the-same
- https://medium.com/@foundev/event-sourcing-and-system-of-record-b919714512b8

**Comment by agentlewis** [comment]
:)
